//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "ai_messages")]
#[ts(rename = "AiMessages")]
#[ts(export)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub conversation_id: String,
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub tool_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tool_input_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tool_data_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub proposal_json: Option<String>,
    pub message_order: i32,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_conversations::Entity",
        from = "Column::ConversationId",
        to = "super::ai_conversations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AiConversations,
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
