//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "campaigns")]
#[ts(rename = "Campaigns")]
#[ts(export)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub system: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub settings_json: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ai_conversations::Entity")]
    AiConversations,
    #[sea_orm(has_many = "super::characters::Entity")]
    Characters,
    #[sea_orm(has_many = "super::heroes::Entity")]
    Heroes,
    #[sea_orm(has_many = "super::locations::Entity")]
    Locations,
    #[sea_orm(has_many = "super::organizations::Entity")]
    Organizations,
    #[sea_orm(has_many = "super::players::Entity")]
    Players,
    #[sea_orm(has_many = "super::quests::Entity")]
    Quests,
    #[sea_orm(has_many = "super::relationships::Entity")]
    Relationships,
    #[sea_orm(has_many = "super::secrets::Entity")]
    Secrets,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::tags::Entity")]
    Tags,
    #[sea_orm(has_many = "super::timeline_events::Entity")]
    TimelineEvents,
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl Related<super::heroes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Heroes.def()
    }
}

impl Related<super::locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Locations.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Players.def()
    }
}

impl Related<super::quests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Quests.def()
    }
}

impl Related<super::relationships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Relationships.def()
    }
}

impl Related<super::secrets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Secrets.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tags.def()
    }
}

impl Related<super::timeline_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimelineEvents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
