//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "players")]
#[ts(rename = "Players")]
#[ts(export)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub campaign_id: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub preferences: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub boundaries: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::campaigns::Entity",
        from = "Column::CampaignId",
        to = "super::campaigns::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Campaigns,
    #[sea_orm(has_many = "super::heroes::Entity")]
    Heroes,
}

impl Related<super::campaigns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Campaigns.def()
    }
}

impl Related<super::heroes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Heroes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
