//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "secrets")]
#[ts(rename = "Secrets")]
#[ts(export)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub campaign_id: String,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub related_entity_type: Option<String>,
    pub related_entity_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub known_by: Option<String>,
    pub revealed: bool,
    pub revealed_in_session: Option<i32>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::campaigns::Entity",
        from = "Column::CampaignId",
        to = "super::campaigns::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Campaigns,
}

impl Related<super::campaigns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Campaigns.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
