// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiConversations = { id: string, campaign_id: string, context_type: string, total_input_tokens: number, total_output_tokens: number, total_cache_read_tokens: number, total_cache_creation_tokens: number, created_at: string, updated_at: string, agent_messages_json: string | null, };
