// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Characters = { id: string, campaign_id: string, name: string, lineage: string | null, occupation: string | null, is_alive: boolean, description: string | null, personality: string | null, motivations: string | null, secrets: string | null, voice_notes: string | null, stat_block_json: string | null, created_at: string, updated_at: string, };
