// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Heroes = { id: string, campaign_id: string, player_id: string | null, name: string, lineage: string | null, classes: string | null, description: string | null, backstory: string | null, goals: string | null, bonds: string | null, is_active: boolean, created_at: string, updated_at: string, };
