// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Relationships = { id: string, campaign_id: string, source_type: string, source_id: string, target_type: string, target_id: string, relationship_type: string, description: string | null, is_bidirectional: boolean, strength: number | null, is_public: boolean, created_at: string, updated_at: string, };
