// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Secrets = { id: string, campaign_id: string, title: string, content: string, related_entity_type: string | null, related_entity_id: string | null, known_by: string | null, revealed: boolean, revealed_in_session: number | null, created_at: string, updated_at: string, };
