// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiMessages = { id: string, conversation_id: string, role: string, content: string, tool_name: string | null, tool_input_json: string | null, tool_data_json: string | null, proposal_json: string | null, message_order: number, created_at: string, };
