// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for entity-scoped queries (relationships, tags)
 */
export type EntityScopedInput = { entity_type: string, entity_id: string, };
