// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for getting location children
 */
export type GetChildrenInput = { parent_id: string, };
