// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for listing entities by campaign
 */
export type ListByCampaignInput = { campaign_id: string, };
