// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Locations = { id: string, campaign_id: string, parent_id: string | null, name: string, location_type: string, description: string | null, detail_level: number, gm_notes: string | null, created_at: string, updated_at: string, };
