// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Organizations = { id: string, campaign_id: string, name: string, org_type: string, description: string | null, goals: string | null, resources: string | null, reputation: string | null, secrets: string | null, is_active: boolean, created_at: string, updated_at: string, };
