// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for search
 */
export type SearchInput = { campaign_id: string, query: string, entity_types: Array<string> | null, limit: number | null, };
