// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tags = { id: string, campaign_id: string, name: string, color: string | null, created_at: string, };
