// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineEvents = { id: string, campaign_id: string, date_display: string, sort_order: bigint, title: string, description: string | null, significance: string, is_public: boolean, created_at: string, updated_at: string, };
